### ISSUE TITLE
PriorityQueue   get error

### ISSUE THREAD

**Issue by sjyttkl** [ajaech/query_completion#5]
in beam.py  file

"class BeamItem  " need to  amend    follows：

```

class BeamItem(object):
    """This is a node in the beam search tree.

    Each node holds four things: a log probability, a list of previous words, and
    the two hidden state vectors.
    """

    def __init__(self, prev_word, prev_hidden, log_prob=0.0):
        self.log_probs = log_prob
        if type(prev_word) == list:
            self.words = prev_word
        else:
            self.words = [prev_word]
        self.prev_hidden = prev_hidden

    **def __le__(self, other):
        return self.log_probs <= other.log_probs

    def __lt__(self, other):
        return self.log_probs < other.log_probs

    def __ge__(self, other):
        return self.log_probs >= other.log_probs

    def __gt__(self, other):
        return self.log_probs > other.log_probs**

    # 重定义等于比较
    def __eq__(self, other):
        return self.log_probs == other.log_probs

    def __str__(self):
        return "beam {0:.3f}: ".format(self.log_probs) + ''.join(self.words)


```
because  PriorityQueue  has Priority feature 。so ，it need add compare  function。

**Comment by ajaech** [comment]
Thanks for raising this issue. Are you sure it's necessary? Does the priority queue get the priority from line 51 on beam.py?

**Comment by sjyttkl** [comment]
I am sure  necessary。   because ,it can raise runtime Exception in python3 environment .  follows:

`Traceback (most recent call last):
  File "dynamic.py", line 150, in <module>
    beam_size=100, stop=stop)  # always use userid=0
  File "/home/jovyan/project/query_completion/code/beam.py", line 144, in GetCompletions
    new_nodes.Insert(new_beam)
  File "/home/jovyan/project/query_completion/code/beam.py", line 71, in Insert
    self.Eject()
  File "/home/jovyan/project/query_completion/code/beam.py", line 82, in Eject
    score, _ = self.q.get()
  File "/opt/conda/lib/python3.7/queue.py", line 180, in get
    item = self._get()
  File "/opt/conda/lib/python3.7/queue.py", line 236, in _get
    return heappop(self.queue)
TypeError: '<' not supported between instances of 'BeamItem' and 'BeamItem'`


The exception above is due to the PriorityQueue . It has no function of comparison. So if we add some code, we can give the queue a right function

**Comment by ajaech** [comment]
I added your suggested change. Thanks for reporting this!
